listen: ':8080'
login:
  id: 'discord app id'
  token: 'discord token'
  redirectUrl: 'redirect url'
  baseUrl: 'base url'
  adminId: 'admin user id'
  guild:
    id: 'guild id'
    roles:
      - 'required role id'
# EndDate uses RFC3339 format: 2006-01-02T15:04:05Z
endDate: 2023-12-12T00:00:00Z
# random seed number
seed: 387429472
